Add: Messenger
polydice/react-live-chat-loader pull request #1
Opened 2020-02-14 09:59 UTC by FateXRebirth

2020-02-24 05:59 UTC, dlackty requested changes

2020-02-24 05:59 UTC, dlackty commented on README.md
> +To use Messenger import the `LiveChatLoaderProvider` and set the `provider` prop
或許改成這樣比較順？

To use Messenger, import the `LiveChatLoaderProvider` and then set the `provider` prop as `messenger`,  the `providerKey` prop as your Facebook App ID, and the `pageID` prop as your Facebook Page ID.

In addition, you can set an optional `locale` prop, and the default value is `en_US`.

2020-02-24 05:59 UTC, dlackty commented on README.md
> +More locale information,
For list of `locale` option  value, please refer to [Facebook Localization document](https://developers.facebook.com/docs/internationalization).

2020-02-24 05:59 UTC, dlackty commented on src/hooks/useChat.js
> +    if(provider && provider === 'messenger' && !pageID) {
if 後面可能多個空白？

2020-02-24 05:59 UTC, dlackty commented on src/index.js
> +  locale: 'en_US',
這個應該是只有 Messenger 會用到，或許不是放在 LiveChatLoaderProvider 做 default props

2020-02-24 05:59 UTC, dlackty commented on src/providers/messenger.js
> +const open = () => {}
這個可能還是要實作一下？

2020-02-24 06:08 UTC, achinchen approved these changes

2020-02-24 06:08 UTC, achinchen commented on src/components/Messenger/index.js
> +  return (
`return state === STATES.COMPLETE ? null : <div /* .... */ />l;`

2020-02-24 06:08 UTC, achinchen commented on src/index.js
> +  const value = {...props, state, setState}
`const value = {state, setState, ...props}`

2020-02-24 06:11 UTC, achinchen commented on src/providers/messenger.js
> +const close = () => {}
close & open 看是不是應該實作，如果不實做可能留個 comment 告知原因。

2020-02-24 07:36 UTC, dlackty approved these changes

2020-02-24 07:36 UTC, dlackty commented on src/components/Messenger/index.js
> +  return (
這個應該是這專案原本其他 provider 的寫法？

2021-04-12 06:19 UTC, FateXRebirth commented
後來直接用官方那邊的 https://github.com/calibreapp/react-live-chat-loader

2021-04-12 06:20 UTC, closed without merging